# Generated by Django 4.2.6 on 2023-10-12 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
