# Generated by Django 4.2.3 on 2023-10-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_comments_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
