# Generated by Django 4.2.5 on 2023-10-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_shared_with'),
        ('posts', '0004_alter_post_shared_with'),
    ]

    operations = [
    ]
